### PR TITLE
Update armstrong_number.c

### PR DESCRIPTION
**Pull request by anurag01a**
- Removed space before int main()
- Added indentation and space for easy code readability

### CODE REVIEW

**Comment by Bhupendrapt5** [comment]
Squash your all PR into single one

**Comment by anurag01a** [comment]
How do I do this in github as i am not having remote git?

**Comment by Bhupendrapt5** [comment]
merge your PR into your own repo and then make a single request

**Comment by anurag01a** [comment]
Yes Sir, it was auto-forked into my github repo then only I made this PR.

**Pull request closed without merging**
