### PR TITLE
Added searching and sorting datastrucutres in C++

### PR DESCRIPTION
**Pull request by soham-dixit**
Added binary search, quick sort and counting sort data structures in C++.

### CODE REVIEW

**Comment by soham-dixit** [comment]
Kindly review it and merge it if everything is alright @Bhupendrapt5.

**Comment by Bhupendrapt5** [comment]
Please add your programs in respective language dir. If it doesn't exist, create one.

**Comment by soham-dixit** [comment]
Sure. Updated and pulled a request. Kindly have a look again. Thank you @Bhupendrapt5

**Comment by Soham7270** [comment]
Please add **hacktoberfest-accepted** label to this PR so it would be displayed on my hacktoberfest dashboard.

**Pull request closed without merging**
